name: 'Auto Tag Dart Versions'
description: 'Automatically create tags when you update your pubspec.yaml version'
author: 'jpeiffer'
inputs:
  changelog:
    description: 'Set to false to skip scanning the changelog to apply the message.'
    required: false
    default: 'true'
  major:
    description: 'Set to false to skip creating the tag for the major version.'
    required: false
    default: 'true'
  minor:
    description: 'Set to false to skip creating the tag for the minor version.'
    required: false
    default: 'true'
  overwrite:
    description: 'Set to false to abort if the existing semver tag exists.'
    required: false
    default: 'true'
  path:
    description: 'Path to the directory containing the pubspec.yaml file to monitor.'
    required: false
    default: .
  prefix:
    description: 'Prefix to apply to the version number'
    required: false
    default: 'v'
  token:
    description: 'The GitHub access token to allow file reading and tag creation.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1

    - name: Update dependencies
      shell: bash
      run: |
        set -e

        dart pub global activate -sgit https://github.com/peiffer-innovations/actions-dart-version-autotag
        dart pub global run dart_version_autotag:tag --token ${{ inputs.token }} --path ${{ inputs.path }} --prefix "${{ inputs.prefix }}" --repository ${{ github.repository }} --changelog ${{inputs.changelog}} --major ${{inputs.major}} --minor ${{inputs.minor}} --overwrite ${{inputs.overwrite}}
